#동서발전 개발버전 설정값
spring:
  #서버: ewp-server-embeded(내장) | ewp-server-user(사용자) | ewp-server-admin(관리자) | ewp-server-monitor(현황판) | ewp-server-converter(변환)
  profiles:
    include: ewp-server-embeded
  datasource:
  # 내부 DB
    plms:
      username: root
      #jdbc-url: jdbc:log4jdbc:mariadb://172.30.1.242:3306/EWP_PLMS?allowMultiQueries=true
      #password: fhEh1q2w3e!
      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/EWP_PLMS?allowMultiQueries=true
      password: 1234
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  # 회의실 관리 DB
    room:
      driver-class-name: com.tmax.tibero.jdbc.TbDriver
      jdbc-url: jdbc:tibero:thin:@vvv.iptime.org:11629:TAC
      username: ewp_meeting
      password: fhEh1q2w3e!
  # 인사 DB
    hr:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@vvv.iptime.org:11521:xe
      username: ewp_meeting
      password: fhEh1q2w3e!
  # SMS DB
    sms:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:sqlserver://vvv.iptime.org:11433;databaseName=mssqltest
      username: mssqltest
      password: fhEh1q2w3e!
  # 동서 메신저 DB
    messenger:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:oracle:thin:@vvv.iptime.org:11521:xe
      username: ewp_meeting
      password: fhEh1q2w3e!
  mail:
    host: outbound.daouoffice.com
    port: 25
    username: system@plms.com
    password: "fhEh1q2w3e!"
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          ssl:
            protocols: "TLSv1.2"
          auth: true
          starttls:
            enable: true
server:
  port-table:
    service-server: 8443
    admin-server: 8443
    monitor-server: 8443
    encoding-server: 8443
config:
  alarm:
    host: https://172.30.1.242
    mail:
      enabled: false
    sms:
      enabled: true
      callback: 070-5000-8125
      #default-receiver: 01027686802
    messenger:
      enabled: true
      #default-receiver: ict21002
  login:
    sso:
      #현재 로그인 상태를 검증할 URL
      validationUrl: http://192.168.0.35:9040/login
      #SSO 로그인이 가능한 페이지 URL
      #pageUrl: http://172.30.1.214:9040/sso/login
      pageUrl: http://192.168.0.35:9040/sso/login
      client-id: "89ff1dd4b6664c8993374b20020431bc"
      client-secret: "6igd5avjfb1mtr27jft2awywc"
      picture-url: 
    plte:
      remote-ip: 172.30.1.242
      picutre-domain: 
  drm:
    enabled: false
    key-path: C:\home\DRM_API\fsdinit
    key: "0100000000001025"
    trans-path: \drm
  reserve:
    #회의 개시시간
    open-time: "08:00"
    #회의 마감시간
    close-time: "18:00"
    #회의 시간간격(분단위)
    interval-minute: 60
    #최대 연속 예약 가능 일수
    consecutive-limit: 100
    #자동승인 허용여부
    auto-approval: true
  file:
    #파일 업로드 경로
    upload-path: C:\B-PLMS\uploadFile\